### ISSUE TITLE
The block contain unexpected or invalid content 

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentytwo#227] opened 2021-11-11 10:07 UTC
Here is the screenshot of the issues,
![image](https://user-images.githubusercontent.com/13062231/141279190-ade97c10-6a9f-459c-9890-fad105f2f9e9.png)
Layered images with duotime block show this issue in the block editor.

**Comment by jffng** [comment] 2021-11-11 15:53
I'm unable to reproduce this on WordPress trunk, or 9.8.2 with Gutenberg trunk. Could you share your environment details? Thank you!

**Comment by jffng** [comment] 2021-11-17 13:23
Going to close this one but please re-open with environment details if the issue persists, thanks!

**Closed as completed by jffng** 2021-11-17 13:23 UTC
Labels: [Type] Bug
