### ISSUE TITLE
Full Site editing is not saving changes.

### ISSUE THREAD

**Issue by irvingbennett** [WordPress/twentytwentytwo#274] opened 2021-12-03 19:52 UTC
**Describe the bug**
I have repeteadly tried to add the find widget to my header in Twenty Twenty-two. And other changes as well.

**To Reproduce**
1. Go to appearance -> FSE
2. Click on Header, add widget (search in this case)
3. Click "Save"
4. See error: open a new window and visit site: search should be visible in the header. It's not there... 

**Expected behavior**
If we edit a theme in FSE, the change should stick when "save" is selected.

**Screenshots**

**Device inphone:**
 - Device: laptop
 - OS: Windows 11 
 - Browser: chrome
 - Version: latest

**Additional context**

**Comment by kjellr** [comment] 2021-12-06 14:44
Hi there, thanks for the report. Can you share the WordPress (andGutenberg, if applicable) version you're using when you see this behavior? Thank you!

**Comment by irvingbennett** [comment] 2021-12-06 15:07
Hi Kjell,I am using  Twenty Twenty-Two Versión: 1.0, Gutenberg
12.0.2, and WordPress 5.9-beta1, in Spanish. I have PHP 5.6 running
on Media Temple Grid system. If there is is any more you need, let me
know, please.Saludos,Irving

----- Original Message -----

**Comment by kjellr** [comment] 2021-12-06 15:20
Thank you, that's helpful! We'll see if someone else can reproduce.

**Comment by kjellr** [comment] 2021-12-06 18:14
I gave this a try, but I had no issues saving the content. Here's what I'm seeing: 

https://user-images.githubusercontent.com/1202812/144899617-e6a45b7d-063f-434c-a7a7-66499edcafe2.mp4

WordPress 5.9 Beta 1, No Gutenberg Plugin installed.

**Comment by lwangdu** [comment] 2021-12-06 19:44
Also, I didn't any issue about this. I wonder that could be your PHP version 6.5.

**Comment by paaljoachim** [comment] 2021-12-07 09:19
Testing:
OSX 11.6.1
Newest Chrome.
Local site running Desktop Server.

I am also able to save when adding a new (Search) block to the header.

**Comment by kjellr** [comment] 2021-12-07 14:47
Ok, since three people haven't been able to reproduce, I think I'm going to close this one for now. If the issue arises again, I think it would make the most sense as a new issue upstream in [the Gutenberg repository](https://github.com/wordpress/gutenberg), since it's unlikely there's something specific to Twenty Twenty-Two that's causing this to happen. 

Thanks!

**Closed as completed by kjellr** 2021-12-07 14:47 UTC
Labels: [Type] Bug, [Status] Needs Testing
