### ISSUE TITLE
Blue rectangle around menu on mobile

### ISSUE THREAD

**Issue by dannymekic** [WordPress/twentytwentytwo#323] opened 2022-01-09 10:57 UTC
**Is your feature request related to a problem? Please describe.**
When I open the theme on a mobile phone and expand the navigation bar, a blue rectangle is visible around the "Home" menu item, even if I'm on another page (such as the "About" page, for example).

![image](https://user-images.githubusercontent.com/19377807/148679328-56dcde92-3029-41f3-8c01-73c134e4176a.png)

When you then click a menu item to open it, a blue rectangle appears around the entire menu.

![image](https://user-images.githubusercontent.com/19377807/148679275-6696b908-241b-4888-bb8b-467effb49790.png)

Both a blue rectangle around a menu item other than the page that is open, and a blue rectangle around the entire menu, do not seem desirable to me.

**Describe the solution you'd like**
It is desirable that the blue rectangle does not appear anywhere.

**Comment by kjellr** [comment] 2022-01-10 12:35
Hi, @dannymekic thanks for the report. What you're seeing here is your browser's default focus styles. The navigation here is powered entirely by Gutenberg's Navigation block, so there's nothing the theme is doing (or probably should do) to change this. 

I'm not personally aware of the thinking and development that went into the focus behavior for the menu, but @jasmussen, in case you know: Is this the expected behavior? If not, we can move this issue upstream to [the Gutenberg repository](https://github.com/WordPress/gutenberg).

**Comment by jasmussen** [comment] 2022-01-10 13:06
Hey, thanks for the report, thanks for the ping! The overlay menu is technically a [modal dialog](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html) which in order to be accessible comes with a few built-in behaviors, one of which is that the first interactive element inside should receive focus, which is what happens here. I'd love to see us build additional styling options for focus that both themes and users can access.

I'm curious about the focus around the entire overlay menu, though, I can't actually reproduce that. If you can find steps to repeat that running [the latest Gutenberg plugin](https://wordpress.org/plugins/gutenberg/), I would very much appreciate a ticket in [the Gutenberg repository](https://github.com/WordPress/gutenberg). You can CC me (@jasmussen) on the ticket, and I'll take a look.

**Comment by jasmussen** [comment] 2022-01-10 13:10
Oh I see it on Safari only now, I'll take a look:

<img width="686" alt="Screenshot 2022-01-10 at 14 10 07" src="https://user-images.githubusercontent.com/1204802/148771350-693ab603-4d8c-4b90-a6ce-9183014163b0.png">

**Comment by dannymekic** [comment] 2022-01-10 13:16
@kjellr @jasmussen Thanks for the quick reply! 

@jasmussen I am testing the theme running at the official Wordpress repository https://2022.wordpress.net/ - so I guess that the latest Gutenberg plugin is running there.

Steps to reproduce:
1. Visit https://2022.wordpress.net/ on an iPhone with Safari or Chrome
2. Press the menu-icon in the right top corner (two flat stripes)
3. The menu opens with "Home" always selected/focused, even if a different page (About, Event, Film) is opened) thus leading to confusion: the desired end state here would either be to not have any of the menu items being 'focused' or, if that's not possible, to have the menu item being 'focused' that belongs to the page currently open
4. When I click somewhere on the white area left of the menu items OR click on one of the menu items to open it, the large light blue rectangle selection area appears:

https://user-images.githubusercontent.com/19377807/148771992-e0a6d25f-0925-4cf3-8be2-f2b6558d0bc4.MP4

**Comment by carolinan** [comment] 2022-01-10 13:25
I believe the focus is correct. It should be on the first menu item, not the current page, because if it was on the current page, 
users may end up with a focus in the middle of a menu and it would seem like the menu changed, which would make it more difficult to navigate.

**Comment by jasmussen** [comment] 2022-01-10 13:35
I created a fix in https://github.com/WordPress/gutenberg/pull/37824.

**Comment by kjellr** [comment] 2022-01-20 16:59
This was fixed upstream in https://github.com/WordPress/gutenberg/pull/37824, so I'm going to close the issue here. Thanks, everyone!

**Closed as completed by kjellr** 2022-01-20 16:59 UTC
