### ISSUE TITLE
appearanceTools to theme.json — is it working?

### ISSUE THREAD

**Issue by bgardner** [WordPress/twentytwentytwo#266] opened 2021-11-30 14:03 UTC
**Describe the bug**
After loading TT2 on a fresh WP install, I do not believe that this setting is working properly. Re: #263 

**To Reproduce**
1. Go to any block that this setting should support (like group border, padding, etc).
2. Try to use the setting.
3. See nothing.

**Expected behavior**
We should see settings such as border, margin, padding, line height—but I fail to see them.

**Comment by kjellr** [comment] 2021-11-30 14:39
Would you mind sharing which version of WordPress + Gutenberg you're running? 

The controls will only show up if you're running Gutenberg 12.1 (via the Gutenberg repository's `trunk` branch, since 12.1 hasn't been released yet), or WordPress 5.9 Beta 1 (which is planned for today).

**Comment by bgardner** [comment] 2021-11-30 14:41
I am running Gutenberg 12.0.1, the most stable version. While I see the original issue shows a Milestone of 12.1 for that setting, it is also mentioned in the 12.0.0 release notes, and covered in the WP Tavern article about 12.0.0.

**Style**
theme.json: Adds a setting property that enables some other ones. (36246)

**Comment by kjellr** [comment] 2021-11-30 15:09
I'm don't think it actually did make it into that release. 

I just tested against Gutenberg `trunk`, and this works just fine there: 

<img width="1049" alt="Screen Shot 2021-11-30 at 10 01 09 AM" src="https://user-images.githubusercontent.com/1202812/144072040-5ac533e7-1c7b-4eea-b5f7-cd4becc5fbff.png">

I do not see those options when I test WordPress `trunk` against https://github.com/WordPress/wordpress-develop/pull/1970. @jffng can you confirm?

**Comment by bgardner** [comment] 2021-11-30 15:16
Yeah, I am chatting with Ryan Welcher now about this in Slack. It was confusing b/c there were a few PR's submitted to address this, one had 12.0.0 milestone and the other 12.1.0. Guessing it was accidentally added to the 12.0.0 Release Notes when, as you mention, it did not make it in. I presume we can close this issue if all of that is true.

**Comment by ryanwelcher** [comment] 2021-11-30 16:00
I can't find any references to the code that those PRs introduce in the plugin. It's safe to say that they didn't make it in. I have updated the [release notes](https://github.com/WordPress/gutenberg/releases/tag/v12.0.0) and the [release post ](https://make.wordpress.org/core/2021/11/29/whats-new-in-gutenberg-12-0-0-24-november/)accordingly.

Thanks, everyone!

**Comment by jffng** [comment] 2021-11-30 16:01
> I do not see those options when I test WordPress trunk against WordPress/wordpress-develop#1970.

I can confirm the appearance of the controls in WordPress trunk + using the `appearanceTools` flag (the #1970 branch), but I had to rebase the branch: 

<img width="1792" alt="Screen Shot 2021-11-30 at 10 59 35 AM" src="https://user-images.githubusercontent.com/5375500/144082363-521c2233-ced2-4834-ad94-f14b1f8cf9db.png">

**Comment by kjellr** [comment] 2021-11-30 16:03
Alright, I think we're good to close this out for now then. Thanks for the report and for testing!

**Closed as completed by kjellr** 2021-11-30 16:03 UTC
Labels: [Type] Bug
