### ISSUE TITLE
Not able to read the text of Pattern 

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentytwo#226] opened 2021-11-11 09:58 UTC
**Describe the bug**
While adding a Large header pattern on the page, I am not able to read the text. 

**To Reproduce**
1. Go to Pages > Add New 
2. Click on Content area and add patterns
3. Add Large Header pattern 
4. See an error

**Screenshots**
Here is the screenshot.
![Screenshot_2](https://user-images.githubusercontent.com/13062231/141277946-9433af54-f24f-4c5f-a822-0c6e0d6bbcf5.png)

**Comment by jffng** [comment] 2021-11-11 15:53
Hi @kafleg, could you share your environment details? I'm unable to reproduce this on WordPress trunk, or 9.8.2 with Gutenberg trunk.

**Comment by jffng** [comment] 2021-11-17 13:23
Going to close this one but please re-open with environment details if the issue persists, thanks!

**Closed as completed by jffng** 2021-11-17 13:23 UTC
Labels: [Type] Bug
