### ISSUE TITLE
Featured Image section missing on Posts and Pages

### ISSUE THREAD

**Issue by mjsdiaz** [WordPress/twentytwentytwo#273] opened 2021-12-03 19:08 UTC
**Describe the bug**
With WP 5.9-beta1 with Twenty Twenty-Two block theme, and when editing a Post (All Posts > Hello World), I don’t see the section to add the Featured Image in the Post Settings sidebar.
If I switch to Twenty Twenty-One, the Featured Image section is there, and if I activate the Gutenberg plugin, the Featured Image section is there in the sidebar.

**To Reproduce**
1. Go to 'Posts > All Posts > Hello World (or any other added post)'
2. Click on 'Settings > Posts sidebar'
3. Scroll down to 'Featured Image section'
4. It's not there

**Expected behavior**
Section to add Featured Image should be in the Set
![post-twenty-twenty-one](https://user-images.githubusercontent.com/2387875/144658724-f9064b23-263f-4180-b922-54bb78c88a2b.png)
![post-twenty-twenty-two](https://user-images.githubusercontent.com/2387875/144658727-c2e12987-5c11-4e4c-8bf6-7e95b80da276.png)
tings sidebar

**Screenshots**
Attached are screenshots of Twenty Twenty-Two and Twenty Twenty-One

**Device:**
 - Device: Mac Mini
 - OS: Mac OS Big Sur 11.6
 - Browser: Chrome iVersion 96.0.4664.55 (Official Build) (x86_64) and FireFox 94.0.2 (64bit)
 - Version:

**Additional context**

**Comment by lwangdu** [comment] 2021-12-04 16:43
Same here on the WP 5.9 Bate 1.

**Comment by kjellr** [comment] 2021-12-06 18:05
Thanks for the reports! I can confirm. If I add `add_theme_support( 'post-thumbnails' );` to the theme, then this works again. 

I'm wondering if maybe https://github.com/WordPress/gutenberg/pull/35593 didn't make its way over to core. @youknowriad or @noisysocks, can you confirm?

**Comment by noisysocks** [comment] 2021-12-07 04:01
Yes looks like https://github.com/WordPress/gutenberg/pull/35593 was missed while adding the [FSE infrastructure to Core](https://core.trac.wordpress.org/ticket/54335). @ockham: Are you able to look into adding that?

**Comment by paaljoachim** [comment] 2021-12-07 09:14
Does this have anything to do with it? (Related to TT1 but the same issue might be also for Twenty Twenty Two.)
https://github.com/joedolson/my-calendar/issues/197#issuecomment-986306781

"...I assume that block themes don't have current_theme_supports( 'post-thumbnails' ), because that block would be added on demand or something? How does that work? "

**Comment by kjellr** [comment] 2021-12-07 13:11
> "...I assume that block themes don't have current_theme_supports( 'post-thumbnails' ), because that block would be added on demand or something? How does that work? "

It's possible. That is it's supposed to be added by default for Block Themes but in the Beta it is currently not happening.

**Comment by lwangdu** [comment] 2021-12-07 15:11
I have tested with TT1 but the feature images works fine. I think something to do with the TT2 theme.

**Comment by kjellr** [comment] 2021-12-07 15:26
Unlike Twenty Twenty-One, Twenty Twenty-Two relies on core opting it in by default. So this will be fixed once https://github.com/WordPress/gutenberg/pull/35593 is migrated into core.

**Comment by noisysocks** [comment] 2021-12-07 23:54
I opened https://core.trac.wordpress.org/ticket/54597 to track this.

**Comment by elbsegler63** [comment] 2021-12-08 08:49
it is also missing in Beta 2

**Comment by kjellr** [comment] 2021-12-08 12:42
Thanks! I'm going to close this now that it's tracked in https://core.trac.wordpress.org/ticket/54597.

**Closed as completed by kjellr** 2021-12-08 12:42 UTC
Labels: [Type] Bug, [Status] Needs Testing
